using System;

namespace UUM.Api.Interfaces
{
    /// <summary>
    ///     Common properties for all users generated by plugins.
    ///     Each plugin may freely define additional attributes in its implementation.
    /// </summary>
    public interface IUserInSource : IIdentifiable
    {
        /// <summary>
        ///     The Guid of the plugin parameters that was used to create this user in source.
        ///     Identifies which plugin instance created this item. Used for serialization.
        /// </summary>
        Guid PluginId { get; }

        /// <summary>
        ///     The login for the target system, must be unique within the target system.
        ///     Used for associating local users from the remote users on update for example.
        /// </summary>
        //string LoginName { get; }
    }
}